window.DIPLOMATIC_VOCABULARY = {
  english: [
    {word:'Hello',arabic:'مرحبًا',pronunciation:'هِلو',level:'A1',category:'daily'},
    {word:'Good morning',arabic:'صباح الخير',pronunciation:'غُد مورنِنغ',level:'A1',category:'daily'},
    {word:'Family',arabic:'عائلة',pronunciation:'فامِلي',level:'A1',category:'daily'},
    {word:'Friend',arabic:'صديق',pronunciation:'فرِند',level:'A1',category:'daily'},
    {word:'Country',arabic:'دولة / بلد',pronunciation:'كَنتري',level:'A1',category:'geography'},
    {word:'City',arabic:'مدينة',pronunciation:'سِتي',level:'A1',category:'geography'},
    {word:'Government',arabic:'حكومة',pronunciation:'غَفِرنمِنت',level:'A2',category:'politics'},
    {word:'President',arabic:'رئيس',pronunciation:'برِزِدَنت',level:'A2',category:'politics'},
    {word:'Election',arabic:'انتخابات',pronunciation:'إلِكشَن',level:'A2',category:'politics'},
    {word:'Embassy',arabic:'سفارة',pronunciation:'إمبَسي',level:'B1',category:'diplomacy'},
    {word:'Ambassador',arabic:'سفير',pronunciation:'أمباسَدَر',level:'B1',category:'diplomacy'},
    {word:'Diplomacy',arabic:'الدبلوماسية',pronunciation:'دِبلومَسي',level:'B1',category:'diplomacy'},
    {word:'Foreign policy',arabic:'السياسة الخارجية',pronunciation:'فورِن بولِسي',level:'B1',category:'diplomacy'},
    {word:'Treaty',arabic:'معاهدة',pronunciation:'تريتي',level:'B1',category:'diplomacy'},
    {word:'Negotiation',arabic:'تفاوض',pronunciation:'نِغوشييشن',level:'B2',category:'diplomacy'},
    {word:'Alliance',arabic:'تحالف',pronunciation:'ألايَنس',level:'B2',category:'international-relations'},
    {word:'Sovereignty',arabic:'السيادة',pronunciation:'سوفْرِنْتي',level:'B2',category:'international-relations'},
    {word:'Sanctions',arabic:'عقوبات',pronunciation:'سانكشِنز',level:'B2',category:'politics'},
    {word:'Ceasefire',arabic:'وقف إطلاق النار',pronunciation:'سيس فاير',level:'B2',category:'security'},
    {word:'Deterrence',arabic:'الردع',pronunciation:'دِتِرَنس',level:'C1',category:'security'}
  ],
  french: [
    {word:'Bonjour',arabic:'مرحبًا / صباح الخير',pronunciation:'بونجور',level:'A1',category:'daily'},
    {word:'Merci',arabic:'شكرًا',pronunciation:'ميرسي',level:'A1',category:'daily'},
    {word:'Famille',arabic:'عائلة',pronunciation:'فاميي',level:'A1',category:'daily'},
    {word:'Ami',arabic:'صديق',pronunciation:'أمي',level:'A1',category:'daily'},
    {word:'Pays',arabic:'دولة / بلد',pronunciation:'بيي',level:'A1',category:'geography'},
    {word:'Ville',arabic:'مدينة',pronunciation:'فيل',level:'A1',category:'geography'},
    {word:'Gouvernement',arabic:'حكومة',pronunciation:'غوفيرنُمان',level:'A2',category:'politics'},
    {word:'Président',arabic:'رئيس',pronunciation:'بريزيدان',level:'A2',category:'politics'},
    {word:'Élection',arabic:'انتخابات',pronunciation:'إليكسيون',level:'A2',category:'politics'},
    {word:'Ambassade',arabic:'سفارة',pronunciation:'أمباساد',level:'B1',category:'diplomacy'},
    {word:'Ambassadeur',arabic:'سفير',pronunciation:'أمباسادور',level:'B1',category:'diplomacy'},
    {word:'Diplomatie',arabic:'الدبلوماسية',pronunciation:'ديبلوماتي',level:'B1',category:'diplomacy'},
    {word:'Politique étrangère',arabic:'السياسة الخارجية',pronunciation:'بوليتيك إيترانجير',level:'B1',category:'diplomacy'},
    {word:'Traité',arabic:'معاهدة',pronunciation:'تريتي',level:'B1',category:'diplomacy'},
    {word:'Négociation',arabic:'تفاوض',pronunciation:'نيغوسْياسيون',level:'B2',category:'diplomacy'},
    {word:'Alliance',arabic:'تحالف',pronunciation:'أليانس',level:'B2',category:'international-relations'},
    {word:'Souveraineté',arabic:'السيادة',pronunciation:'سوفيرينتي',level:'B2',category:'international-relations'},
    {word:'Sanctions',arabic:'عقوبات',pronunciation:'سانكسيون',level:'B2',category:'politics'},
    {word:'Cessez-le-feu',arabic:'وقف إطلاق النار',pronunciation:'سيسيه لُ فو',level:'B2',category:'security'},
    {word:'Dissuasion',arabic:'الردع',pronunciation:'ديسوازيون',level:'C1',category:'security'}
  ],
  spanish: [
    {word:'Hola',arabic:'مرحبًا',pronunciation:'أولا',level:'A1',category:'daily'},
    {word:'Gracias',arabic:'شكرًا',pronunciation:'غراسياس',level:'A1',category:'daily'},
    {word:'Familia',arabic:'عائلة',pronunciation:'فاميليا',level:'A1',category:'daily'},
    {word:'Amigo',arabic:'صديق',pronunciation:'أميغو',level:'A1',category:'daily'},
    {word:'País',arabic:'دولة / بلد',pronunciation:'باييس',level:'A1',category:'geography'},
    {word:'Ciudad',arabic:'مدينة',pronunciation:'ثيوداد / سيوداد',level:'A1',category:'geography'},
    {word:'Gobierno',arabic:'حكومة',pronunciation:'غوبييرنو',level:'A2',category:'politics'},
    {word:'Presidente',arabic:'رئيس',pronunciation:'بريسيدينتي',level:'A2',category:'politics'},
    {word:'Elección',arabic:'انتخابات',pronunciation:'إليكثيون / إليكسيون',level:'A2',category:'politics'},
    {word:'Embajada',arabic:'سفارة',pronunciation:'إمباخادا',level:'B1',category:'diplomacy'},
    {word:'Embajador',arabic:'سفير',pronunciation:'إمباخادور',level:'B1',category:'diplomacy'},
    {word:'Diplomacia',arabic:'الدبلوماسية',pronunciation:'ديبلوماسيا',level:'B1',category:'diplomacy'},
    {word:'Política exterior',arabic:'السياسة الخارجية',pronunciation:'بوليتيكا إكستيريور',level:'B1',category:'diplomacy'},
    {word:'Tratado',arabic:'معاهدة',pronunciation:'تراتادو',level:'B1',category:'diplomacy'},
    {word:'Negociación',arabic:'تفاوض',pronunciation:'نيغوثياثيون / نيغوسياسيون',level:'B2',category:'diplomacy'},
    {word:'Alianza',arabic:'تحالف',pronunciation:'أليانثا / أليانسا',level:'B2',category:'international-relations'},
    {word:'Soberanía',arabic:'السيادة',pronunciation:'سوبيرانيا',level:'B2',category:'international-relations'},
    {word:'Sanciones',arabic:'عقوبات',pronunciation:'سانثيونيس / سانسيونيس',level:'B2',category:'politics'},
    {word:'Alto el fuego',arabic:'وقف إطلاق النار',pronunciation:'ألتو إل فويغو',level:'B2',category:'security'},
    {word:'Disuasión',arabic:'الردع',pronunciation:'ديسواثيون / ديسواسيون',level:'C1',category:'security'}
  ]
};